### ISSUE TITLE
Doc Issue:EMDK For Xamarin

### ISSUE THREAD

**Issue by darryncampbell** [EMDK/xamarin-docs#2]
Page: http://emdk.github.io/xamarin-docs/edge/#guide-tutorial-helloxamarin

"Next we will to add and interface to our Activity"
Should read:
"Next we will _need_ to add an~~d~~ interface to our Activity"

**Comment by bhecox** [comment]
Thanks Darryn, fixed this issue.

http://emdk.github.io/xamarin-docs/edge/#guide-tutorial-helloxamarin
