### ISSUE TITLE
Length1/Length2 for decoders needs elaboration

### ISSUE THREAD

**Issue by mkstephenson** [EMDK/xamarin-docs#4]
The ScannerConfig.DecoderParams object contains the configs for the various barcode decoders. For the decoders where you can configure the barcode lengths, these config objects also contain two properties, Length1 and Length2. Both have the comment:

> "Use to set decode lengths. The valid range is 0 to 55."

I assume one is minimum barcode length and one is maximum barcode length but I have absolutely no idea which is which, would it be possible to elaborate on which one does which?

**Comment by mkstephenson** [comment]
Ok, after a bit of investigation, I found that Length1 is the minimum length and Length2 is the maximum length, you measure from Length1 and up to but not including Length2 (so to include barcode lengths 7, 8 and 9 you would set Length1 to 7 and Length2 to 10

**Comment by bhecox** [comment]
Hey Michael, For Development assistance please make use of our developer community developer.zebra.com
