### ISSUE TITLE
404 error when installing Xamarin EMDK Component

### ISSUE THREAD

**Issue by ryanholden8** [EMDK/xamarin-docs#6]
Unable to install version 2.4.0.87. Older versions install fine. It's unclear to me how to find out what url is returning the 404. On Windows 10 running latest VS 2017. Attached is a screenshot of the error.

![emdk-404-error](https://user-images.githubusercontent.com/10402627/28973574-9ec21af8-7901-11e7-9b43-48de35aa6dae.png)

**Comment by npj473** [comment]
Hi @ryanholden8 ,
Right version for VS2017 is 2.4.0.94, request to download from visual studio gallery.
2.4.0.87 is for VS2013 and VS2015

Thanks,
Praveen.N
